### ISSUE TITLE
При входе на сервер, получаю это:

### ISSUE THREAD

**Issue by glowgrew** [DonDays/ProtocolTags#1]
`[ProtocolTags] Plugin ProtocolTags v1.1a generated an exception while executing task 116
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
	at ru.dondays.protocoltags.packetwrapper.WrapperPlayServerScoreboardTeam.getPlayers(WrapperPlayServerScoreboardTeam.java:96) ~[?:?]
	at ru.dondays.protocoltags.api.TagPacket.addPlayer(TagPacket.java:62) ~[?:?]
	at ru.dondays.protocoltags.api.TagData.addPlayer(TagData.java:41) ~[?:?]
	at ru.dondays.protocoltags.api.TagManager.setTag(TagManager.java:43) ~[?:?]
	at ru.dondays.protocoltags.api.TagManager.setTag(TagManager.java:22) ~[?:?]
	at ru.dondays.protocoltags.ProtocolTags.setTags(ProtocolTags.java:36) ~[?:?]
	at ru.dondays.protocoltags.listeners.PlayerListener.lambda$onJoin$1(PlayerListener.java:21) ~[?:?]
	at ru.dondays.protocoltags.listeners.PlayerListener$$Lambda$32/21773613.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-65a0347-a552117]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]` Скинул только ошибку.

**Comment by DonDays** [comment]
Будет исправлено в ближайшее время

**Comment by DonDays** [comment]
Исправлено.
